/*
 * lzdatagen - LZ data generator
 *
 * Copyright 2016 Joergen Ibsen
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#include "lzdatagen.h"

#include <assert.h>
#include <math.h>
#include <string.h>

#include "pcg_basic.h"

/* Limits for length values, based on zlib */
#define MIN_LEN 3
#define MAX_LEN 258
#define NUM_LEN (MAX_LEN - MIN_LEN + 1)

/* Number of lengths to generate at a time */
#define LEN_PER_CHUNK 512

/**
 * Generate random double.
 *
 * @note Not perfectly distributed, but more than adequate for this use.
 *
 * @return random double in range [0;1)
 */
static double
rand_double(void)
{
	return pcg32_random() / (UINT32_MAX + 1.0);
}

/**
 * Generate random literals.
 *
 * Generate literals following a power distribution. If `lit_exp` is 1.0, the
 * distribution is linear. As `lit_exp` grows, the likelihood of small values
 * increases.
 *
 * @param ptr pointer to where to store literals
 * @param size number of literals to generate
 * @param lit_exp exponent used for distribution
 */
static void
generate_literals(unsigned char *ptr, size_t size, double lit_exp)
{
	size_t i;

	for (i = 0; i < size; ++i) {
		ptr[i] = (unsigned char) (256 * pow(rand_double(), lit_exp));
	}
}

/**
 * Generate random lengths.
 *
 * Generate length frequencies following a power distribution. If `len_exp` is
 * 1.0, the distribution is linear. As `len_exp` grows, the likelihood of small
 * values increases.
 *
 * @note The size of the frequency table is `NUM_LEN`, the range of possible
 * length values, while `num` is the number of length values to generate.
 *
 * @param len_freq pointer to where to store length frequencies
 * @param num number of lengths to generate
 * @param len_exp exponent used for distribution
 */
static void
generate_lengths(unsigned int len_freq[NUM_LEN], size_t num, double len_exp)
{
	size_t i;

	for (i = 0; i < NUM_LEN; ++i) {
		len_freq[i] = 0;
	}

	for (i = 0; i < num; ++i) {
		size_t len = (size_t) (NUM_LEN * pow(rand_double(), len_exp));

		assert(len < NUM_LEN);

		len_freq[len]++;
	}
}

/**
 * Generate compressible data.
 *
 * Data is generated by inserting sequences of either random bytes or
 * repetitions from a buffer of bytes, depending on the ratio parameter.
 *
 * Based on "SDGen: Mimicking Datasets for Content Generation in Storage
 * Benchmarks" by Raúl Gracia-Tinedo et al. (https://www.usenix.org/node/188461)
 *
 * Instead of sampling actual data, this uses a simple power function to
 * determine the distributions of literals values and match lenghts.
 *
 * @param ptr pointer to where to store generated data
 * @param size number of bytes to generate
 * @param ratio desired compression ratio
 * @param len_exp exponent used for distribution of lenghts
 * @param lit_exp exponent used for distribution of literals
 */
void
lzdg_generate_data(void *ptr, size_t size, double ratio, double len_exp, double lit_exp)
{
	unsigned int len_freq[NUM_LEN];
	unsigned char buffer[MAX_LEN];
	unsigned char *p = ptr;
	size_t cur_len = 0;
	size_t i = 0;
	int last_was_match = 0;

	len_freq[0] = 0;

	while (i < size) {
		size_t len;

		/* Find next length with non-zero frequency */
		while (len_freq[cur_len] == 0) {
			if (cur_len == 0) {
				generate_literals(buffer, MAX_LEN, lit_exp);

				generate_lengths(len_freq, LEN_PER_CHUNK, len_exp);

				cur_len = NUM_LEN;
			}

			cur_len--;
		}

		len = MIN_LEN + cur_len;

		len_freq[cur_len]--;

		if (len > size - i) {
			len = size - i;
		}

		if (rand_double() < 1.0 / ratio) {
			/* Insert len literals */
			generate_literals(p, len, lit_exp);

			last_was_match = 0;
		}
		else {
			/* Insert literal to break up matches */
			if (last_was_match) {
				generate_literals(p, 1, lit_exp);
				i++;
				p++;

				if (len > size - i) {
					len = size - i;
				}
			}

			/* Insert match of length len */
			memcpy(p, buffer, len);

			last_was_match = 1;
		}

		i += len;
		p += len;
	}
}
